//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.DeliveryEngine.WindowsService.LeadProcessingDeliveryWorkflowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeadProcessingDeliveryWorkflowService.ILeadProcessingDeliveryWorkflowService")]
    public interface ILeadProcessingDeliveryWorkflowService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ILeadProcessingDeliveryWorkflowService/ProcessLeads")]
        void ProcessLeads(EDDY.IS.DeliveryEngine.Entity.DeliveryLeadData LeadData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeadProcessingDeliveryWorkflowServiceChannel : EDDY.IS.DeliveryEngine.WindowsService.LeadProcessingDeliveryWorkflowService.ILeadProcessingDeliveryWorkflowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeadProcessingDeliveryWorkflowServiceClient : System.ServiceModel.ClientBase<EDDY.IS.DeliveryEngine.WindowsService.LeadProcessingDeliveryWorkflowService.ILeadProcessingDeliveryWorkflowService>, EDDY.IS.DeliveryEngine.WindowsService.LeadProcessingDeliveryWorkflowService.ILeadProcessingDeliveryWorkflowService {
        
        public LeadProcessingDeliveryWorkflowServiceClient() {
        }
        
        public LeadProcessingDeliveryWorkflowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeadProcessingDeliveryWorkflowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadProcessingDeliveryWorkflowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadProcessingDeliveryWorkflowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ProcessLeads(EDDY.IS.DeliveryEngine.Entity.DeliveryLeadData LeadData) {
            base.Channel.ProcessLeads(LeadData);
        }
    }
}
