//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.DeliveryEngine.WindowsService.BatchLeadProcessingWorkflowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BatchLeadProcessingWorkflowService.BatchLeadDeliveryWorkflowService")]
    public interface BatchLeadDeliveryWorkflowService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/BatchLeadDeliveryWorkflowService/processBatch")]
        void processBatch(int deliveryEndpointId, int productId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BatchLeadDeliveryWorkflowServiceChannel : EDDY.IS.DeliveryEngine.WindowsService.BatchLeadProcessingWorkflowService.BatchLeadDeliveryWorkflowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BatchLeadDeliveryWorkflowServiceClient : System.ServiceModel.ClientBase<EDDY.IS.DeliveryEngine.WindowsService.BatchLeadProcessingWorkflowService.BatchLeadDeliveryWorkflowService>, EDDY.IS.DeliveryEngine.WindowsService.BatchLeadProcessingWorkflowService.BatchLeadDeliveryWorkflowService {
        
        public BatchLeadDeliveryWorkflowServiceClient() {
        }
        
        public BatchLeadDeliveryWorkflowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BatchLeadDeliveryWorkflowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatchLeadDeliveryWorkflowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BatchLeadDeliveryWorkflowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void processBatch(int deliveryEndpointId, int productId) {
            base.Channel.processBatch(deliveryEndpointId, productId);
        }
    }
}
