//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.DeliveryEngine.Test.RetryLeadDeliveryWorkflowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RetryLeadDeliveryWorkflowService.IRetryLeadDeliveryWorkflowService")]
    public interface IRetryLeadDeliveryWorkflowService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRetryLeadDeliveryWorkflowService/RetryProcessLeads")]
        void RetryProcessLeads(EDDY.IS.DeliveryEngine.Entity.RealtimeDeliveryQueueItem RealtimeDeliveryQueueItem, EDDY.IS.DeliveryEngine.Entity.DeliveryLeadData LeadData, int DeliveryEndpointId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRetryLeadDeliveryWorkflowServiceChannel : EDDY.IS.DeliveryEngine.Test.RetryLeadDeliveryWorkflowService.IRetryLeadDeliveryWorkflowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetryLeadDeliveryWorkflowServiceClient : System.ServiceModel.ClientBase<EDDY.IS.DeliveryEngine.Test.RetryLeadDeliveryWorkflowService.IRetryLeadDeliveryWorkflowService>, EDDY.IS.DeliveryEngine.Test.RetryLeadDeliveryWorkflowService.IRetryLeadDeliveryWorkflowService {
        
        public RetryLeadDeliveryWorkflowServiceClient() {
        }
        
        public RetryLeadDeliveryWorkflowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RetryLeadDeliveryWorkflowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetryLeadDeliveryWorkflowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RetryLeadDeliveryWorkflowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RetryProcessLeads(EDDY.IS.DeliveryEngine.Entity.RealtimeDeliveryQueueItem RealtimeDeliveryQueueItem, EDDY.IS.DeliveryEngine.Entity.DeliveryLeadData LeadData, int DeliveryEndpointId) {
            base.Channel.RetryProcessLeads(RealtimeDeliveryQueueItem, LeadData, DeliveryEndpointId);
        }
    }
}
