//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.DeliveryEngine.WindowsService.LeadPreviewWorkflowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeadPreviewWorkflowService.ILeadPreviewWorkflowNewService")]
    public interface ILeadPreviewWorkflowNewService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadPreviewWorkflowNewService/ProcessPreview", ReplyAction="http://tempuri.org/ILeadPreviewWorkflowNewService/ProcessPreviewResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Result")]
        System.Collections.Generic.Dictionary<string, string> ProcessPreview(EDDY.IS.DeliveryEngine.Entity.DeliveryLeadData LeadData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeadPreviewWorkflowNewServiceChannel : EDDY.IS.DeliveryEngine.WindowsService.LeadPreviewWorkflowService.ILeadPreviewWorkflowNewService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeadPreviewWorkflowNewServiceClient : System.ServiceModel.ClientBase<EDDY.IS.DeliveryEngine.WindowsService.LeadPreviewWorkflowService.ILeadPreviewWorkflowNewService>, EDDY.IS.DeliveryEngine.WindowsService.LeadPreviewWorkflowService.ILeadPreviewWorkflowNewService {
        
        public LeadPreviewWorkflowNewServiceClient() {
        }
        
        public LeadPreviewWorkflowNewServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeadPreviewWorkflowNewServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadPreviewWorkflowNewServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadPreviewWorkflowNewServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, string> ProcessPreview(EDDY.IS.DeliveryEngine.Entity.DeliveryLeadData LeadData) {
            return base.Channel.ProcessPreview(LeadData);
        }
    }
}
